#deployment values
serviceName: checkoutservice
serviceCount: 1
imageName: gcr.io/google-samples/microservices-demo/checkoutservice
imageTag: v0.2.3
servicePort: 5050
containerVars: 
  - name: PORT
    value: 5050
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:5000"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"
#service values
servicePortType: ClusterIP
hostPort: 5050