#deployment values
serviceName: redis-cart
serviceCount: 1
imageName: redis:alpine
servicePort: 6379
serviceMontPath: /data
volumeName: redis-data
  
  
#service values
servicePortType: ClusterIP
hostPort: 7070