apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
spec:
  type: {{.Values.appServiceType}}
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: {{.Values.appPort}}
      targetPort: {{.Values.appTargetPort}}
      nodePort: {{.Values.appNodePort}}