apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devcluster
  region: us-east-1

managedNodeGroups:
  - name: devnode
    instanceType: t2.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
