apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-map
data:
  mongodb: mongodb-0.mongodb-headless.default.svc.cluster.local:27017
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  mongo-username: cm9vdA==
  mongo-password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoui-deployment
  labels:
    app: mongoui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoui
  template:
    metadata:
      labels:
        app: mongoui
    spec:
      containers:
        - name: mongoui
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-map
                key: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongoui-service
spec:
  selector:
    app: mongoui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000