apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
spec:
  type: {{.Values.servicePortType}}
  selector:
    app: {{.Values.serviceName}}
  ports:
    - protocol: TCP
      port: {{.Values.hostPort}}
      targetPort: {{.Values.servicePort}}